course3.homework2
w0id/Chat pull request #4
Opened 2022-04-26 23:24 UTC by w0id

2022-04-29 14:29 UTC, efserg requested changes
Нет, тут нужен рефакторинг.
Пока не принято!

2022-04-29 14:29 UTC, efserg commented on src/main/java/ru/gb/chat/server/InMemoryAuthService.java
>  public class InMemoryAuthService implements AuthService {
Имя класса как бы намекает, что авторизация происходит из данных, которые лежат в памяти. Каково же был мое удивление, когда я увидел, что тут лезут в базу

2022-04-29 14:29 UTC, efserg commented on src/main/java/ru/gb/chat/server/InMemoryAuthService.java
> +        try (Connection connection = DriverManager.getConnection("jdbc:sqlite:chat.db")) {
Ну вот зачем создавать подключение на каждый запрос?

2022-04-29 14:42 UTC, w0id commented on src/main/java/ru/gb/chat/server/InMemoryAuthService.java
>  public class InMemoryAuthService implements AuthService {
Переименовать класс, а подключение вынести в конструктор? Я правильно понял?

2022-05-01 06:09 UTC, efserg requested changes
Уберите лишний код, все это сбивает с толку

2022-05-01 06:09 UTC, efserg commented on src/main/java/ru/gb/chat/server/SQLAuthService.java
> +    }
Это тут зачем?

2022-05-01 06:09 UTC, efserg commented on src/main/java/ru/gb/chat/server/SQLAuthService.java
> +    private final List<UserData> users;
Не понимаю, зачем это?

2022-05-01 11:04 UTC, merged